"""update

Revision ID: 02fa0d7e614f
Revises: 6106cc614341
Create Date: 2021-09-19 12:46:07.976463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fa0d7e614f'
down_revision = '6106cc614341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downvotes', 'downvote')
    op.drop_column('upvotes', 'upvote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('upvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('downvotes', sa.Column('downvote', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
